### ISSUE TITLE
link to the presentations

### ISSUE THREAD

**Issue by mvidonne** [RMLio/prov4itdata-web-app#1]
In the [technical documentation](https://prov4itdata.ilabt.imec.be/docs/), the links to the presentations [1](https://prov4itdata.ilabt.imec.be/docs/assets/presentation-kgc2021.pdf) and [2](https://prov4itdata.ilabt.imec.be/docs/assets/presentation-www2021.pdf)  are  not available

**Comment by bjdmeest** [comment]
Woops, typo in the links, fixed, thanks for the catch!
